### ISSUE TITLE
Full frontend code review

### ISSUE THREAD

**Issue by vincerubinetti** [greenelab/annorxiver-journal-recommender#47]
A bunch of PRs on the frontend were merged without code review from @dongbohu due to time constraints, and I said we'd have him do a full review of the code at the end.

**Comment by vincerubinetti** [comment]
Reminder to future me: `CI=true` in github actions config should be `false`, because i'm setting it `false` before the build anyway.

**Comment by dongbohu** [comment]
I reviewed the frontend code and have the following comments:
* https://github.com/greenelab/annorxiver-journal-recommender/blob/3a53de9064dea1b429e28e852ae3f9c23012137d/frontend/src/about.js#L14 `This tool` to `It`.
* https://github.com/greenelab/annorxiver-journal-recommender/blob/3a53de9064dea1b429e28e852ae3f9c23012137d/frontend/src/backend.js#L3 `lookup` to `look up`
* https://github.com/greenelab/annorxiver-journal-recommender/blob/3a53de9064dea1b429e28e852ae3f9c23012137d/frontend/src/backend.js#L21 `lookup` to `look up`
* https://github.com/greenelab/annorxiver-journal-recommender/blob/3a53de9064dea1b429e28e852ae3f9c23012137d/frontend/src/backend.js#L50 `lookup` to `look up`
* https://github.com/greenelab/annorxiver-journal-recommender/blob/3a53de9064dea1b429e28e852ae3f9c23012137d/frontend/src/backend.js#L71 Sorting may not be necessary, because the results in API response are already sorted by `distance`.

* https://github.com/greenelab/annorxiver-journal-recommender/blob/3a53de9064dea1b429e28e852ae3f9c23012137d/frontend/src/header.js#L12 `AnnoRxver` to `AnnoRxiver`
